[build]
  command = "yarn deploy"
  functions = "functions"
  publish   = "out_publish"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  CHEC_PUBLIC_KEY = "pk_18819955a96172d911ddeab7e489f3b2966610816db9b"
  CHEC_API_URL = "https://api.chec.io"
  CHEC_SECRET_KEY = "sk_18819c9e9216c971b16fbffdff6257e402ea312931339"
  STRIPE_SECRET = "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"
  NODE_ENV = ""